apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-app.fullname" . }}-secret
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  {{ .Values.secrets.mypassword.key }}: {{ .Values.secrets.mypassword.value | default "" | b64enc | quote }}
